---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    post:
      summary: Create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '400':
          description: bad request
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                nickname:
                  type: string
                phone:
                  type: integer
                  nullable: true
                password:
                  type: string
              required:
              - email
              - nickname
              - password
  "/api/v1/login":
    post:
      summary: Log in
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Log in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/auto_login":
    get:
      summary: Automatic log in
      tags:
      - Users
      security:
      - Bearer: []
      responses:
        '200':
          description: log in
        '401':
          description: Access token is missing or invalid
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    Bearer:
      description: Client token
      type: http
      scheme: bearer
      name: Authorization
      in: header
